# Title shown in Application Information tab.
title: "DLS Resource Manager Stack"
# Sub Title shown in Application Information tab.
description: "DLS Resource Manager Stack"
schemaVersion: 1.1.0
version: "1.0"
locale: "en"
variableGroups:
  - title: "Hidden"
    variables:
      - compartment_name
      - tenancy_ocid
      - user_ocid
      - region
      - fingerprint
      - private_key_path
      - non_admin_users
    visible: false
  - title: "Provision in"
    variables:
      - ${region}
      - ${compartment_name}
    visible: false
  - title: "IAM Groups/Policies Configuration"
    variables:
      - dls_group_name
      - dls_dynamic_group_name
      - dls_root_policy_name

variables:
  region:
    type: oci:identity:region:name
    required: true
    visible: true
  compartment_name:
    type: oci:identity:compartment:name
    required: true
    title: "Compartment"
    visible: true
  tenancy_ocid:
    type: string
    required: true
    visible: false
  non_admin_users:
    type: arrayschema.yaml
    items:
      type: string
    required: false
    title: "OCIDs of Non Admin Users to be added to the DataLabelingGroup"
    description: "Comma separated list of OCID strings"
  dls_group_name:
    type: string
    title: "Group Name for security policies"
    description: "Do not use spaces."
    required: true
    default: "DataLabelingGroup"
    pattern: "^[a-zA-Z0-9]+$"
  dls_dynamic_group_name:
    type: string
    title: "Dynamic Group Name for Data Labeling Service resources"
    description: "Do not use spaces."
    required: true
    default: "DataLabelingDynamicGroup"
    pattern: "^[a-zA-Z0-9]+$"
  dls_root_policy_name:
    type: string
    title: "Root Policy Name (Tenancy Level)"
    description: "Do not use spaces"
    required: true
    default: "DataLabelingRootPolicies"
    pattern: "^[a-zA-Z0-9]+$"
